config/routes.rb
Rails.application.routes.draw do

devise_for :users
devise_scope :user do
  authenticated :user do
    root to: 'todo_list#index', as: :authenticated_root
  end

  unauthenticated do
    root to: 'devise/sessions#new', as: :unauthenticated_root
  end
end

get 'todo_lists', to: 'todo_list#index'
get 'todo_lists/new', to: 'todo_list#new'
post 'todo_lists', to: 'todo_list#create'
delete 'todo_lists', to: 'todo_list#delete'

get 'todos', to: 'todos#index'
get 'todos/new', to: 'todos#new'
post 'todos', to: 'todos#create'
delete 'todos', to: 'todos#delete'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :todo_list
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  has_many :todos
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :todo_lists
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_list_controller.rb
class TodoListController < ApplicationController

  def index
    page = params[:page] || 1
      @todolists = TodoList.order(written_at: :desc).page(page).per(5)
      render :index
  end

  def new

  end

  def create
  end

  def delete
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todolist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>



<body>
  <div class="container">
    <div class="row">
      <h1> Todo List Application </h1>
      <p class="notice"><%= flash[:notice] %></p>
      <p class="alert"><%= flash[:alert] %></p>
    </div>
    <div class="row">
      <div class="sidebar col-xs-2">
        <ul class="list-unstyled">
          <% if current_user %>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete,
                            class: 'btn btn-warning' %></li>
    
          <% end %>

        </ul>
      </div>
      <div class="main-content col-xs-10">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/todo_list/index.html.erb
<h2>Todo Lists</h2>

<div class="todo_lists">
  <% @todolists.each do |todo_list| %>
  <div class="todos">
    <li><%= link_to "Add New Todo List", todo_lists_new_path, class: 'btn btn-info' %></li>

    <h2><%= link_to_unless_current todo_list.title, todo_lists_path(todos) %></h2>
      <h3>Written on: <%= todo_list.written_at %></h3>
        <% unless todo_list.todos.count.zero? %>
          <h3>
            Tagged as:
              <% todo_lists.todos.map do |todos| %>
                <%= link_to todos.name, todos_path(todos.name) %>,
              <% end %>
          </h3>
        <% end %>

      <%= simple_format(todos.content) %>
  </div>

    <!-- <%= render partial: "post", object: post %> -->
    <!-- <%= render partial: "todos", locals: { todos: todos } %> -->
  <% end %>
</div>

<%= paginate @todolists %>